### ISSUE TITLE
ksm sdk python returns errors

### ISSUE THREAD

**Issue by 2948GEN** [Keeper-Security/secrets-manager#372]
Running a simple python script using SDK library to get secrets from secrets manager (based on the as code presented in Usage example of the documentation)  returns a TypeError.

In keeper_secrets_manager_core/core.py, line 573:  the value returned by the method self.config.get(ConfigKeys.KEY_CLIENT_KEY) is None, so it throws a TypeError exception when given to url_safe_str_to_bytes function.

See python tracebacks below for more details:

Traceback (most recent call last):
  File "tests/test_ksm.py", line 5, in <module>
    all_secrets = secrets_manager.get_secrets()
  File "/home/sam/autopylot/venv/lib/python3.8/site-packages/keeper_secrets_manager_core/core.py", line 639, in get_secrets
    records_resp = self.fetch_and_decrypt_secrets(uids)
  File "/home/sam/autopylot/venv/lib/python3.8/site-packages/keeper_secrets_manager_core/core.py", line 573, in fetch_and_decrypt_secrets
    client_key = url_safe_str_to_bytes(self.config.get(ConfigKeys.KEY_CLIENT_KEY))
  File "/home/sam/autopylot/venv/lib/python3.8/site-packages/keeper_secrets_manager_core/utils.py", line 71, in url_safe_str_to_bytes
    b = base64.urlsafe_b64decode(s + '==')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Environment information:
- package keeper-secrets-manager-core in version 16.3.5
- python version: 3.8.10
- OS: Linux Ubuntu 20.04 LTS (codename: focal)

**Comment by jsupun** [comment]
So the problem is the `SecretsManager()` constructor and `get_secrets()` methods were not called together initially. For example, when you were testing you called SecretsManager() and then exited. Then added the get_secrets(), and re-ran the application.

On the second run, it detected the JSON config existed and assume it had been bound. Since the `clientKey` is only needed to bind the application, it is removed. Later in the code, since the appKey doesn't exists yet, it will attempt to decode the encrypted app key, but we have removed the `clientKey` so it breaks.

The work around for this is to delete the JSON config file, get a new one-time access token, and run your application with both `SecretsManager()` and  `get_secrets()`. In the end you should have an `appKey` key in the JSON.

**Comment by 2948GEN** [comment]
Thanks @jsupun for your help. Indeed, SecretsManager() constructor and get_secrets() method were used within two different files (using python import). Your work around works perfectly.
